# Generated by Django 6.0.1 on 2026-01-30 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_user_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='min_stock_level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='supplier',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='stockalert',
            name='alert_type',
            field=models.CharField(choices=[('low_stock', 'Low Stock'), ('expired', 'Expired'), ('other', 'Other')], default='low_stock', max_length=30),
        ),
        migrations.AlterField(
            model_name='stockalert',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='stockalert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_stock_alerts', to=settings.AUTH_USER_MODEL),
        ),
    ]
