# Generated by Django 6.0.1 on 2026-01-30 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_accessory_receipt_alter_accessory_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='location',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='min_stock_level',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='supplier',
        ),
    ]
