# Generated by Django 6.0.1 on 2026-02-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='min_stock_level',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
