# Generated by Django 6.0.1 on 2026-02-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_min_stock_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='supplier',
            field=models.CharField(max_length=100, blank=True),
        ),
    ]
