# Generated by Django 6.0.1 on 2026-02-02 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_update_vehicle_type_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='stockalert',
            name='alert_type',
            field=models.CharField(choices=[('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock'), ('reorder', 'Reorder Required')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stockalert',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stockalert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('gasoline', 'Gasoline'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['-created_at'], name='api_activit_created_61fc37_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['activity_type'], name='api_activit_activit_017d24_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['user'], name='api_activit_user_id_bb4ccc_idx'),
        ),
    ]
