# Generated by Django 6.0.3 on 2026-03-07 19:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_vehicle_vin'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('liters', models.DecimalField(decimal_places=2, help_text='Amount of fuel in liters', max_digits=10)),
                ('price_per_liter', models.DecimalField(decimal_places=2, help_text='Price per liter', max_digits=10)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('odometer', models.IntegerField(help_text='Odometer reading at time of fill-up')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_records', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_usage', to='api.vehicle')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
