# Generated by Django 6.0.3 on 2026-03-07 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_add_fuel_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='repairrecord',
            name='driver_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='repairrecord',
            name='driver_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='repairrecord',
            name='driver_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repairrecord',
            name='driver_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_repairs', to=settings.AUTH_USER_MODEL),
        ),
    ]
