# Generated by Django 6.0.3 on 2026-03-16 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_add_driver_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='vehicles',
            field=models.ManyToManyField(blank=True, help_text='Vehicles this accessory can be used for', related_name='accessories', to='api.vehicle'),
        ),
    ]
