# Generated by Django 6.0.3 on 2026-03-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_add_vehicles_to_accessory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakdown',
            name='image',
        ),
        migrations.AddField(
            model_name='breakdown',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
