# Generated by Django 6.0.1 on 2026-01-21 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_alter_breakdown_status_alter_vehicle_driver_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mileage', models.PositiveIntegerField(help_text='Mileage driven today')),
                ('fuel_used', models.DecimalField(decimal_places=2, help_text='Fuel used in liters', max_digits=6)),
                ('route_taken', models.TextField(help_text='Description of the route taken')),
                ('issues', models.TextField(blank=True, help_text='Any issues encountered')),
                ('driver', models.ForeignKey(limit_choices_to={'role': 'DRIVER'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('driver', 'vehicle', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField(help_text='Start date of the week (Monday)')),
                ('summary', models.TextField(help_text='Weekly summary')),
                ('total_mileage', models.PositiveIntegerField(help_text='Total mileage for the week')),
                ('maintenance_needs', models.TextField(blank=True, help_text='Maintenance needs identified')),
                ('performance_notes', models.TextField(blank=True, help_text='Performance notes')),
                ('driver', models.ForeignKey(limit_choices_to={'role': 'DRIVER'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-week_start_date'],
                'unique_together': {('driver', 'vehicle', 'week_start_date')},
            },
        ),
    ]
